In [1]:
import pandas as pd

# Define the file paths
file_paths = {
    'title_basics': '../data/download/title.basics.tsv',
    'title_akas': '../data/download/title.akas.tsv',
    'title_crew': '../data/download/title.crew.tsv',
    'title_episode': '../data/download/title.episode.tsv',
    'title_principals': '../data/download/title.principals.tsv',
    'title_ratings': '../data/download/title.ratings.tsv',
    'name_basics': '../data/download/name.basics.tsv',
}

In [2]:
columns_to_use = {
    'title_basics': ['tconst', 'titleType', 'primaryTitle', 'isAdult', 'startYear', 'runtimeMinutes', 'genres']
}

# Read the first NROWS from the datasets
df_title_basics_all = pd.read_csv(file_paths['title_basics'], usecols=columns_to_use['title_basics'], delimiter='\t', na_values='\\N')

# Display the first few rows
display("df_title_basics",df_title_basics_all.head())

# Find minimum start year
print("Min startYear", df_title_basics_all['startYear'].min())

# Count of ttconst
print("Unique ttconst: ", df_title_basics_all['tconst'].count())

/var/folders/h9/brqpqy9x10q4n_n6230q8s800000gn/T/ipykernel_961/1671667888.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_title_basics_all = pd.read_csv(file_paths['title_basics'], usecols=columns_to_use['title_basics'], delimiter='\t', na_values='\\N')

'df_title_basics'

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0.0,1894.0,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,0.0,1892.0,5.0,"Animation,Short"
2,tt0000003,short,Poor Pierrot,0.0,1892.0,5.0,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,0.0,1892.0,12.0,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,0.0,1893.0,1.0,Short

Min startYear 1874.0
Unique ttconst:  11366522

In [3]:
# Get count of movies which released >= 1990 
df_title_basics_1990 = df_title_basics_all[df_title_basics_all['startYear'] >= 1990]
display(df_title_basics_1990)

# Find maximum start year
print("Max startYear:", df_title_basics_1990['startYear'].max())

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres
919,tt0000929,short,Klebolin klebt alles,0.0,1990.0,NaN,"Comedy,Short"
965,tt0000977,short,Mutterliebe,0.0,1990.0,NaN,Short
11632,tt0011801,movie,Tötet nicht mehr,0.0,2019.0,NaN,"Action,Crime"
15172,tt0015414,movie,La tierra de los toros,0.0,2000.0,60.0,NaN
15480,tt0015724,movie,Dama de noche,0.0,1993.0,102.0,"Drama,Mystery,Romance"
...,...,...,...,...,...,...,...
11366517,tt9916848,tvEpisode,Episode #3.17,0.0,2009.0,NaN,Drama
11366518,tt9916850,tvEpisode,Episode #3.19,0.0,2010.0,NaN,Drama
11366519,tt9916852,tvEpisode,Episode #3.20,0.0,2010.0,NaN,Drama
11366520,tt9916856,short,The Wind,0.0,2015.0,27,Short
11366521,tt9916880,tvEpisode,Horrid Henry Knows It All,0.0,2014.0,10,"Adventure,Animation,Comedy"

Max startYear: 2031.0

In [4]:
# Get movies from 2031  
display(df_title_basics_all[df_title_basics_all['startYear'] == 2031])

del df_title_basics_all

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres
9426078,tt5637536,movie,Avatar 5,0.0,2031.0,NaN,"Action,Adventure,Fantasy"

In [5]:
# Delete movies with startYear > 2024

# Get count of movies which released > 2024
display(df_title_basics_1990[df_title_basics_1990['startYear'] > 2024].count())

# Delete movies with startYear > 2024
df_title_basics_1990_2024 = df_title_basics_1990[df_title_basics_1990['startYear'] <= 2024]

# Display the count of movies which released between 1990 and 2024
display(df_title_basics_1990_2024.head())

tconst            18020
titleType         18020
primaryTitle      18020
isAdult           18020
startYear         18020
runtimeMinutes     3537
genres            17428
dtype: int64

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres
919,tt0000929,short,Klebolin klebt alles,0.0,1990.0,NaN,"Comedy,Short"
965,tt0000977,short,Mutterliebe,0.0,1990.0,NaN,Short
11632,tt0011801,movie,Tötet nicht mehr,0.0,2019.0,NaN,"Action,Crime"
15172,tt0015414,movie,La tierra de los toros,0.0,2000.0,60.0,NaN
15480,tt0015724,movie,Dama de noche,0.0,1993.0,102.0,"Drama,Mystery,Romance"

In [6]:
# Assuming df is your DataFrame
df_html = df_title_basics_1990_2024.head().to_html(classes='table table-striped', index=False, border=0)

# Save the HTML to a file
with open('../report/df_title_basics_1990_2024.html', 'w', encoding='utf-8') as file:
    file.write(df_html)

In [7]:
display(df_title_basics_1990_2024.count())

tconst            8401797
titleType         8401797
primaryTitle      8401784
isAdult           8401797
startYear         8401797
runtimeMinutes    2662387
genres            8108749
dtype: int64

### Ratings

In [8]:
# Set the display format for floating-point numbers
pd.options.display.float_format = '{:.2f}'.format

# Define columns to use
columns_to_use_ratings = ['tconst', 'averageRating', 'numVotes']

# Load the ratings data
df_title_ratings_filtered = pd.read_csv(file_paths['title_ratings'], delimiter='\t', usecols=columns_to_use_ratings, na_values='\\N')

# Display the ratings data
display(df_title_ratings_filtered.head())
display(df_title_ratings_filtered.describe())

      tconst  averageRating  numVotes
0  tt0000001           5.70      2116
1  tt0000002           5.60       285
2  tt0000003           6.40      2152
3  tt0000004           5.30       183
4  tt0000005           6.20      2874

       averageRating   numVotes
count     1521380.00 1521380.00
mean            6.95    1027.07
std             1.39   17793.75
min             1.00       5.00
25%             6.20      11.00
50%             7.10      26.00
75%             7.90     100.00
max            10.00 2989337.00

In [9]:
# Merge the df_title_basics_1990_2024 and ratings data
df_title_basics_1990_2024_ratings = pd.merge(df_title_basics_1990_2024, df_title_ratings_filtered, left_on='tconst', right_on='tconst', how='left')

# Delete the data with missing values in the 'averageRating' column
df_title_basics_1990_2024_ratings = df_title_basics_1990_2024_ratings.dropna(subset=['averageRating'])

# Display the merged data
display(df_title_basics_1990_2024_ratings.head())
display(df_title_basics_1990_2024_ratings.describe())

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000929,short,Klebolin klebt alles,0.00,1990.00,NaN,"Comedy,Short",5.30,48.00
3,tt0015414,movie,La tierra de los toros,0.00,2000.00,60.00,NaN,5.40,17.00
4,tt0015724,movie,Dama de noche,0.00,1993.00,102.00,"Drama,Mystery,Romance",6.30,31.00
5,tt0035423,movie,Kate & Leopold,0.00,2001.00,118.00,"Comedy,Fantasy,Romance",6.40,90993.00
6,tt0038086,movie,Shiva und die Galgenblume,0.00,1993.00,NaN,Thriller,7.00,27.00

         isAdult  startYear  averageRating   numVotes
count 1239710.00 1239710.00     1239710.00 1239710.00
mean        0.01    2012.21           7.03    1096.78
std         0.12       8.67           1.40   18694.51
min         0.00    1990.00           1.00       5.00
25%         0.00    2007.00           6.30      11.00
50%         0.00    2014.00           7.20      24.00
75%         0.00    2019.00           8.00      97.00
max         1.00    2024.00          10.00 2989337.00

### Crew and principals

In [10]:
import pandas as pd

# Define columns to load for each dataset
columns_to_use = {
    'title_crew': ['tconst', 'directors', 'writers'],
}

# Read necessary columns
df_title_crew = pd.read_csv(file_paths['title_crew'], delimiter='\t', usecols=columns_to_use['title_crew'], na_values='\\N')

# Merge datasets
df_title_basics_1990_2024_ratings = df_title_basics_1990_2024_ratings.merge(df_title_crew, on='tconst', how='left')  # Merge crew information

# Display the merged data
display(df_title_basics_1990_2024_ratings)
display(df_title_basics_1990_2024_ratings.describe())

# Save to CSV
df_title_basics_1990_2024_ratings.to_csv('../data/preprocessed/movies_1990_2024.csv', index=False)

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,writers
0,tt0000929,short,Klebolin klebt alles,0.00,1990.00,NaN,"Comedy,Short",5.30,48.00,nm0093361,NaN
1,tt0015414,movie,La tierra de los toros,0.00,2000.00,60.00,NaN,5.40,17.00,nm0615736,NaN
2,tt0015724,movie,Dama de noche,0.00,1993.00,102.00,"Drama,Mystery,Romance",6.30,31.00,nm0529960,"nm0529960,nm1597742"
3,tt0035423,movie,Kate & Leopold,0.00,2001.00,118.00,"Comedy,Fantasy,Romance",6.40,90993.00,nm0003506,"nm0737216,nm0003506"
4,tt0038086,movie,Shiva und die Galgenblume,0.00,1993.00,NaN,Thriller,7.00,27.00,nm0826094,"nm0076617,nm0826094"
...,...,...,...,...,...,...,...,...,...,...,...
1239705,tt9916730,movie,6 Gunn,0.00,2017.00,116,Drama,7.00,12.00,nm10538612,nm10538612
1239706,tt9916766,tvEpisode,Episode #10.15,0.00,2019.00,43,"Family,Game-Show,Reality-TV",7.20,23.00,NaN,NaN
1239707,tt9916778,tvEpisode,Escape,0.00,2019.00,NaN,"Crime,Drama,Mystery",7.20,37.00,NaN,NaN
1239708,tt9916840,tvEpisode,Horrid Henry's Comic Caper,0.00,2014.00,11,"Adventure,Animation,Comedy",6.90,11.00,nm0996406,"nm1482639,nm2586970"
1239709,tt9916880,tvEpisode,Horrid Henry Knows It All,0.00,2014.00,10,"Adventure,Animation,Comedy",7.90,9.00,nm0996406,"nm1482639,nm2586970"

         isAdult  startYear  averageRating   numVotes
count 1239710.00 1239710.00     1239710.00 1239710.00
mean        0.01    2012.21           7.03    1096.78
std         0.12       8.67           1.40   18694.51
min         0.00    1990.00           1.00       5.00
25%         0.00    2007.00           6.30      11.00
50%         0.00    2014.00           7.20      24.00
75%         0.00    2019.00           8.00      97.00
max         1.00    2024.00          10.00 2989337.00

In [11]:
#df = pd.read_csv('../data/preprocessed/movies_1990_2024.csv')
df = df_title_basics_1990_2024_ratings.copy()

In [12]:
# Drop rows with missing values
df = df.dropna(subset=['primaryTitle'])

# Find Toy Story 3 movie
display(df[df['primaryTitle'].str.contains('Toy Story 3', case=False)])

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,writers
101659,tt0435761,movie,Toy Story 3,0.00,2010.00,103.00,"Adventure,Animation,Comedy",8.30,918856.00,nm0881279,"nm0005124,nm0004056,nm0881279,nm1578335,nm0028..."
406344,tt13123076,video,Toy Story 3 in Real Life,0.00,2020.00,99.00,"Adventure,Comedy,Family",8.20,90.00,"nm12110127,nm11910980","nm0005124,nm0004056,nm0881279,nm1578335"
547050,tt1623789,videoGame,Toy Story 3: The Video Game,0.00,2010.00,NaN,"Action,Adventure,Comedy",7.50,1001.00,"nm8990031,nm0881279","nm1733701,nm4196951,nm4196379,nm2458218,nm1134..."
590810,tt1799686,tvEpisode,Toy Story 3,0.00,2010.00,4.00,"Comedy,Short",5.20,18.00,nm3766090,nm3766090
614166,tt1897358,tvEpisode,Toy Story 3,0.00,2010.00,NaN,Talk-Show,6.80,8.00,nm4416167,"nm4791685,nm4416167"
672989,tt2160857,tvEpisode,How Toy Story 3 Should Have Ended,0.00,2011.00,2.00,"Animation,Comedy,Short",7.10,75.00,nm4678619,"nm4678744,nm4678619"
686655,tt2207882,video,Toy Story 3: The Gang's All Here,0.00,2010.00,10.00,"Documentary,Short",6.60,133.00,NaN,NaN
825254,tt2997156,video,Toy Story 3: A Toy's Eye View - Creating a Who...,0.00,2010.00,6.00,Short,6.40,8.00,NaN,NaN
1016703,tt5289646,tvEpisode,Toy Story 3,0.00,2012.00,6.00,"Documentary,Short",7.10,19.00,nm3766090,nm3766090
1079502,tt6296556,tvEpisode,YMS: Toy Story 3,0.00,2011.00,13.00,"Comedy,Talk-Show",6.60,30.00,nm4891409,nm4891409
1128375,tt7252522,tvEpisode,Everything Wrong with Toy Story 3 in 14 Minute...,0.00,2016.00,15.00,Comedy,5.20,18.00,NaN,NaN

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from annoy import AnnoyIndex
import pandas as pd
import numpy as np
import joblib

# Load the dataset
# Ensure `df` is already preloaded with your data
df['combined_features'] = (
    df['primaryTitle'].fillna('') + ' ' +
    df['genres'].fillna('') + ' ' +
    df['directors'].fillna('') + ' ' +
    df['writers'].fillna('')
)

# TF-IDF Vectorization with fewer features
vectorizer = TfidfVectorizer(max_features=1000)
tfidf_matrix = vectorizer.fit_transform(df['combined_features'])

# Dimensionality Reduction
svd = TruncatedSVD(n_components=100, random_state=42)
reduced_matrix = svd.fit_transform(tfidf_matrix)

# Scale numeric features
numeric_features = ['runtimeMinutes', 'numVotes', 'averageRating']
df[numeric_features] = df[numeric_features].fillna(0)
scaler = MinMaxScaler()
scaled_numeric_features = scaler.fit_transform(df[numeric_features])

# Apply weight to numeric features
numeric_weight = 2.0  # Assign a higher weight to numeric features
scaled_numeric_features_weighted = scaled_numeric_features * numeric_weight

# Apply weight to TF-IDF features (genres)
#genre_weight = 0.5  # Lighter weight for genre features
#genre_indices = [vectorizer.get_feature_names_out().tolist().index(genre) for genre in ['action', 'comedy', 'drama']]  # Example genres
#for idx in genre_indices:
#    reduced_matrix[:, idx] *= genre_weight  # Apply the weight to the genre columns in the reduced matrix

# Combine all features
combined_matrix = np.hstack([reduced_matrix, scaled_numeric_features_weighted])

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    combined_matrix, df['averageRating'], test_size=0.2, random_state=42
)

# Train KNN regressor
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)

# Save the model
#joblib.dump(knn, '/Users/stiborv/Documents/NMgr/ZS2425/NDBI048/ipynbs/knn_model_weighted.joblib')


# Predictions and evaluation
y_pred = knn.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Validation Mean Squared Error: {mse:.2f}")
print(f"Validation Mean Absolute Error: {mae:.2f}")

#Validation Mean Squared Error: 0.04
#Validation Mean Absolute Error: 0.10

Validation Mean Squared Error: 0.04
Validation Mean Absolute Error: 0.10

In [14]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.2f}")

from sklearn.metrics import explained_variance_score
ev = explained_variance_score(y_test, y_pred)
print(f"Explained Variance Score: {ev:.2f}")

# R² Score: 0.98
# Explained Variance Score: 0.98

R² Score: 0.98
Explained Variance Score: 0.98

In [15]:
%pip install -q -U kaleido

WARNING: You are using pip version 22.0.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Users/stiborv/.pyenv/versions/3.10.4/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [16]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def visualize_model_performance_plotly(y_true, y_pred, name):
    """
    Visualizes the model's performance using Plotly by plotting predicted vs actual ratings 
    and the error distribution.

    Parameters:
        y_true (array-like): True values of the target variable.
        y_pred (array-like): Predicted values of the target variable.
    """
    # Title dict based on name
    title_dict = {
        "model_performance_plotly": "K-NN Performance",
        "model_performance_plotly_weighted": "K-NN Performance Weighted Votes and Time", 
        "model_performance_plotly_wegited_crew": "K-NN Performance Weighted Crew",
    }

    # Calculate errors
    errors = y_pred - y_true

    # Create subplots
    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=("Predicted vs Actual Ratings", "Error Distribution (Predicted - Actual)"),
        column_widths=[0.5, 0.5],
        horizontal_spacing=0.2,  # Adjust spacing between subplots
    )
    
    # Scatter plot: Predicted vs Actual ratings
    fig.add_trace(
        go.Scatter(
            x=y_true, y=y_pred,
            mode='markers',
            marker=dict(
                color='cornflowerblue',
                size=6,
                opacity=0.6,
            ),
            name="Predicted vs Actual",
            hoverinfo='none'  # Disable hover info for scatter plot
        ),
        row=1, col=1
    )
    # Add diagonal reference line
    fig.add_trace(
        go.Scatter(
            x=[min(y_true), max(y_true)],
            y=[min(y_true), max(y_true)],
            mode='lines',
            line=dict(color='orangered', dash='dash', width=2),
            name="Ideal Prediction",
        ),
        row=1, col=1
    )

    # Histogram: Error distribution
    fig.add_trace(
        go.Histogram(
            x=errors,
            nbinsx=30,
            marker=dict(
                color='mediumorchid',
                line=dict(width=1.5, color='black'),
            ),
            opacity=0.8,
            name="Error Distribution",
        ),
        row=1, col=2
    )
    
    # Customize layout
    fig.update_layout(
        title=dict(
            text=title_dict[name],
            x=0.5, xanchor="center"
        ),
        title_font=dict(size=20, color='black'),
        xaxis=dict(
            title="Actual Ratings",
            title_font=dict(size=12, color='black'),
            gridcolor='lightgray',
            zerolinecolor='gray',
        ),
        yaxis=dict(
            title="Predicted Ratings",
            title_font=dict(size=12, color='black'),
            gridcolor='lightgray',
            zerolinecolor='gray',
        ),
        xaxis2=dict(
            title="Prediction Error",
            title_font=dict(size=12, color='black'),
            gridcolor='lightgray',
            zerolinecolor='gray',
        ),
        yaxis2=dict(
            title="Frequency",
            title_font=dict(size=12, color='black'),
            gridcolor='lightgray',
            zerolinecolor='gray',
        ),
        plot_bgcolor='whitesmoke',
        paper_bgcolor='rgba(0,0,0,0)',
        margin=dict(t=90, b=50, l=50, r=50),
        legend=dict(
            font=dict(size=12),
            bordercolor='gray',
            borderwidth=1,
        ),
        showlegend=True,
    )

    # Adjust subplot titles
    fig.update_annotations(
        font=dict(size=16, color='black'),
        align="center",
        yshift=10 
    )

    # Disable the legend
    fig.for_each_trace(lambda trace: trace.update(showlegend=False))

    # Display the plot
    #fig.show()

    # Save to HTML
    #fig.write_html(f'../report/{name}.html')
    # Save as png
    #fig.write_image(f'../report/{name}.png', scale=3)
    # Save pdf
    #fig.write_image(f'../report/{name}.pdf')
    # Save to svg
    fig.write_image(f'../report/{name}.svg')

# Visualization
#visualize_model_performance_plotly(y_test, y_pred,name="model_performance_plotly_weighted")
#visualize_model_performance_plotly(y_test, y_pred,name="model_performance_plotly")

In [17]:
visualize_model_performance_plotly(y_test, y_pred,name="model_performance_plotly_weighted")

In [18]:
subset_size = 500  # Choose a reasonable number based on your system's capacity
train_subset = X_train[:subset_size]
y_train_subset = y_train[:subset_size]

y_train_pred_subset = knn.predict(train_subset)
train_mse_subset = mean_squared_error(y_train_subset, y_train_pred_subset)
train_mae_subset = mean_absolute_error(y_train_subset, y_train_pred_subset)

print(f"Training Mean Squared Error (Subset): {train_mse_subset:.2f}")
print(f"Training Mean Absolute Error (Subset): {train_mae_subset:.2f}")

#Training Mean Squared Error (Subset): 0.03
#Training Mean Absolute Error (Subset): 0.09

Training Mean Squared Error (Subset): 0.03
Training Mean Absolute Error (Subset): 0.09

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from annoy import AnnoyIndex
import pandas as pd
import numpy as np

# Load the dataset
# Ensure `df` is already preloaded with your data
df['combined_features'] = (
    df['primaryTitle'].fillna('') + ' ' +
    df['genres'].fillna('') + ' ' +
    df['directors'].fillna('') + ' ' +
    df['writers'].fillna('')
)

# TF-IDF Vectorization with fewer features
vectorizer = TfidfVectorizer(max_features=1000)
tfidf_matrix = vectorizer.fit_transform(df['combined_features'])

# Dimensionality Reduction
svd = TruncatedSVD(n_components=100, random_state=42)
reduced_matrix = svd.fit_transform(tfidf_matrix)

# Scale numeric features
numeric_features = ['runtimeMinutes', 'numVotes', 'averageRating']
df[numeric_features] = df[numeric_features].fillna(0)
scaler = MinMaxScaler()
scaled_numeric_features = scaler.fit_transform(df[numeric_features])

# Combine all features
combined_matrix = np.hstack([reduced_matrix, scaled_numeric_features])

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    combined_matrix, df['averageRating'], test_size=0.2, random_state=42
)

# Train KNN regressor
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)

# Predictions and evaluation
y_pred = knn.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Validation Mean Squared Error: {mse:.2f}")
print(f"Validation Mean Absolute Error: {mae:.2f}")

#visualize_model_performance_plotly(y_test, y_pred,name="model_performance_plotly")

Validation Mean Squared Error: 0.14
Validation Mean Absolute Error: 0.18

In [16]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.2f}")

from sklearn.metrics import explained_variance_score
ev = explained_variance_score(y_test, y_pred)
print(f"Explained Variance Score: {ev:.2f}")

R² Score: 0.93
Explained Variance Score: 0.93

In [15]:
subset_size = 500  # Choose a reasonable number based on your system's capacity
train_subset = X_train[:subset_size]
y_train_subset = y_train[:subset_size]

y_train_pred_subset = knn.predict(train_subset)
train_mse_subset = mean_squared_error(y_train_subset, y_train_pred_subset)
train_mae_subset = mean_absolute_error(y_train_subset, y_train_pred_subset)

print(f"Training Mean Squared Error (Subset): {train_mse_subset:.2f}")
print(f"Training Mean Absolute Error (Subset): {train_mae_subset:.2f}")

Training Mean Squared Error (Subset): 0.09
Training Mean Absolute Error (Subset): 0.14

In [15]:
from annoy import AnnoyIndex

# Annoy Index for Fast Similarity Search
dimension = combined_matrix.shape[1]
annoy_index = AnnoyIndex(dimension, metric='angular')
for i, vector in enumerate(combined_matrix):
    annoy_index.add_item(i, vector)
annoy_index.build(10)

# Define the dimension of the reduced matrix
dimension = reduced_matrix.shape[1]

# Find Similar Movies Function
def find_similar_movies_annoy(movie_id, k=5):
    # Check if movie ID exists
    if movie_id not in df['tconst'].values:
        print(f"Movie ID {movie_id} not found in the dataset.")
        return None

    # Get the target movie's startYear
    target_start_year = df[df['tconst'] == movie_id]['startYear'].values[0]

    # Filter movies by startYear condition
    filtered_df = df[df['startYear'] <= target_start_year].reset_index(drop=True)

    # Create a filtered Annoy index
    filtered_index = AnnoyIndex(dimension, metric='angular')
    for i, vector in enumerate(reduced_matrix[filtered_df.index]):
        filtered_index.add_item(i, vector)

    filtered_index.build(10)

    # Get the movie's index in the filtered dataset
    movie_index = filtered_df[filtered_df['tconst'] == movie_id].index[0]

    # Find similar movies
    similar_indices = filtered_index.get_nns_by_item(movie_index, k + 1)
    similar_indices = [i for i in similar_indices if filtered_df.iloc[i]['tconst'] != movie_id][:k]

    if not similar_indices:
        print(f"No similar movies found for {movie_id}.")
        return None

    similar_movies = filtered_df.iloc[similar_indices]
    return similar_movies

# Example Usage
#movie_id = 'tt0944947'  # Replace with your target movie ID
#movie_id = 'tt3720452'   # Amazing Spiderman 2
movie_id = 'tt0435761'   # Toy Story 3
similar_movies = find_similar_movies_annoy(movie_id, k=5)

if similar_movies is not None:
    #print(similar_movies)
    # Print it as normal dataframe
    display(similar_movies)

# Display the movie details
display(df[df['tconst'] == movie_id])

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,writers,combined_features
304412,tt1302032,movie,Teen-Aged,0.00,2008.00,76.00,"Comedy,Drama",5.80,11.00,nm3152572,"nm3153252,nm3152646","Teen-Aged Comedy,Drama nm3152572 nm3153252,nm3..."
3638,tt0102914,movie,Showdown at Williams Creek,0.00,1991.00,96.00,"Drama,Western",6.20,118.00,nm0471862,"nm0336736,nm2239586","Showdown at Williams Creek Drama,Western nm047..."
17859,tt0120217,tvEpisode,"Stone, Scissors, Paper",0.00,1997.00,85.00,Drama,7.50,29.00,nm0926458,nm0131710,"Stone, Scissors, Paper Drama nm0926458 nm0131710"
143802,tt0580681,tvEpisode,Brother's Keeper,0.00,1990.00,0,Drama,7.90,10.00,nm0281058,nm0455673,Brother's Keeper Drama nm0281058 nm0455673
270740,tt11355304,tvSeries,Tian Xia Liang Cang,0.00,2002.00,46.00,"Drama,History",6.40,11.00,nm0943212,nm3279839,"Tian Xia Liang Cang Drama,History nm0943212 nm..."

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,writers,combined_features
101659,tt0435761,movie,Toy Story 3,0.00,2010.00,103.00,"Adventure,Animation,Comedy",8.30,918856.00,nm0881279,"nm0005124,nm0004056,nm0881279,nm1578335,nm0028...","Toy Story 3 Adventure,Animation,Comedy nm08812..."

## Weighted Directors and Writers

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from collections import Counter
import pandas as pd
import numpy as np
import joblib

# Load the dataset
# Ensure `df` is already preloaded with your data
df['combined_features'] = (
    df['primaryTitle'].fillna('') + ' ' +
    df['genres'].fillna('') + ' ' +
    df['directors'].fillna('') + ' ' +
    df['writers'].fillna('')
)

# TF-IDF Vectorization with fewer features
vectorizer = TfidfVectorizer(max_features=1000)
tfidf_matrix = vectorizer.fit_transform(df['combined_features'])

# Dimensionality Reduction
svd = TruncatedSVD(n_components=100, random_state=42)
reduced_matrix = svd.fit_transform(tfidf_matrix)

# Scale numeric features
numeric_features = ['runtimeMinutes', 'numVotes', 'averageRating']
df[numeric_features] = df[numeric_features].fillna(0)
scaler = MinMaxScaler()
scaled_numeric_features = scaler.fit_transform(df[numeric_features])

def get_weighted_directors_writers(df, column_name, rating_column='averageRating'):
    all_values = df[column_name].fillna('').str.split(',').explode().str.strip()
    rating_map = df.groupby(column_name)[rating_column].mean()  # Get average ratings for each director/ writer
    weight_map = rating_map.to_dict()  # Map of director/writer to average rating

    weighted_column = df[column_name].fillna('').apply(
        lambda x: np.mean([weight_map.get(val.strip(), 0) for val in x.split(',')]) if x else 0
    )

    return weighted_column


# Calculate weights for directors and writers
df['directors_weight'] = get_weighted_directors_writers(df, 'directors')
df['writers_weight'] = get_weighted_directors_writers(df, 'writers')

# Combine weights into a single feature
df['directors_writers_weighted'] = df['directors_weight'] + df['writers_weight']

# Now incorporate these weights into the final feature set
scaled_numeric_features_weighted = scaled_numeric_features * df['directors_writers_weighted'].values[:, np.newaxis]

# Combine all features
combined_matrix = np.hstack([reduced_matrix, scaled_numeric_features_weighted])

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    combined_matrix, df['averageRating'], test_size=0.2, random_state=42
)

# Train KNN regressor
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)

# Predictions and evaluation
y_pred = knn.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Validation Mean Squared Error: {mse:.2f}")
print(f"Validation Mean Absolute Error: {mae:.2f}")

Validation Mean Squared Error: 1.05
Validation Mean Absolute Error: 0.72

In [23]:
visualize_model_performance_plotly(y_test, y_pred,name="model_performance_plotly_wegited_crew")

In [24]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.2f}")

from sklearn.metrics import explained_variance_score
ev = explained_variance_score(y_test, y_pred)
print(f"Explained Variance Score: {ev:.2f}")

R² Score: 0.47
Explained Variance Score: 0.47

In [21]:
subset_size = 500  # Choose a reasonable number based on your system's capacity
train_subset = X_train[:subset_size]
y_train_subset = y_train[:subset_size]

y_train_pred_subset = knn.predict(train_subset)
train_mse_subset = mean_squared_error(y_train_subset, y_train_pred_subset)
train_mae_subset = mean_absolute_error(y_train_subset, y_train_pred_subset)

print(f"Training Mean Squared Error (Subset): {train_mse_subset:.2f}")
print(f"Training Mean Absolute Error (Subset): {train_mae_subset:.2f}")

Training Mean Squared Error (Subset): 0.98
Training Mean Absolute Error (Subset): 0.74

In [ ]:
# Compute Nan values in primaryTitle
print(df['primaryTitle'].isnull().sum())
# Drop Nan values in primaryTitle
df = df.dropna(subset=['primaryTitle'])

In [ ]:
# Find movie with title spiderman and sort by numVotes
display(df[df['primaryTitle'].str.contains('Spiderman', case=False)].sort_values(by='numVotes', ascending=False))

In [ ]:
%pip install -q plotly
%pip install -q nbformat
import plotly.io as pio
pio.renderers.default = 'browser'

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Assuming df_title_akas and df_title_ratings are your datasets

# Filter relevant columns and drop missing values
df_akas = df_title_akas[['titleId', 'region', 'language']].dropna()
df_ratings = df_title_ratings[['tconst', 'averageRating']].dropna()

# Merge the datasets on 'titleId'
df_ratings_akas = df_ratings.merge(df_akas, left_on='tconst', right_on='titleId')

# Calculate the top 10 regions with the highest number of unique localized titles
region_counts = df_akas.groupby('region')['titleId'].nunique().sort_values(ascending=False).head(10)

# Calculate the average rating by region and language
region_language_ratings = df_ratings_akas.groupby(['region', 'language'])['averageRating'].mean().reset_index()

# Display the first few rows of the ratings dataset
display("df_title_ratings", df_title_ratings.head())

# Calculate statistics
min_rating = df_title_ratings['averageRating'].min()
max_rating = df_title_ratings['averageRating'].max()
mean_rating = df_title_ratings['averageRating'].mean()
median_rating = df_title_ratings['averageRating'].median()
std_rating = df_title_ratings['averageRating'].std()

print(f"Minimum Rating: {min_rating}")
print(f"Maximum Rating: {max_rating}")
print(f"Mean Rating: {mean_rating}")
print(f"Median Rating: {median_rating}")
print(f"Standard Deviation: {std_rating}")

## Histogram

In [ ]:
import plotly.express as px
import plotly.colors as pc
import pandas as pd
import plotly as py

# Assuming df_title_ratings is already loaded and contains the 'averageRating' column

# Calculate statistics
min_rating = df['averageRating'].min()
max_rating = df['averageRating'].max()
mean_rating = df['averageRating'].mean()
median_rating = df['averageRating'].median()
std_rating = df['averageRating'].std()

# Define the color palette (using a blue tone)
color_palette = pc.sequential.Blues

# Create histogram for average ratings using Plotly
fig_hist = px.histogram(
    df, 
    x='averageRating', 
    nbins=40,  # Adjusting the number of bins for smoother distribution
    title='Distribution of Film Ratings',
    labels={'averageRating': 'Average Rating'},
    color_discrete_sequence=[color_palette[-2]],  # Using a blue color from the palette
)

# Customize the layout for better appearance
fig_hist.update_layout(
    title_font=dict(size=20, color='black'),
    xaxis_title_font=dict(size=14, color='black'),
    yaxis_title_font=dict(size=14, color='black'),
    showlegend=False,
    bargap=0.1,
    plot_bgcolor='whitesmoke',  # Slightly grey background
    paper_bgcolor='rgba(0,0,0,0)',
    margin=dict(t=50, b=100, l=50, r=50),  # Adjust bottom margin for annotation space
    yaxis=dict(
        tickformat=",.0f",  # Remove decimals
        showgrid=True, 
        gridcolor='lightgrey',  # Grey horizontal gridlines
    ),
)

# Add text box for statistics below the histogram
"""
statistics_text = (
    f"Min: {min_rating:.2f}  |  "
    f"Max: {max_rating:.2f}  |  "
    f"Mean: {mean_rating:.2f}  |  "
    f"Median: {median_rating:.2f}  |  "
    f"Mean + Std Dev: {mean_rating + std_rating:.2f}  |  "
    f"Mean - Std Dev: {mean_rating - std_rating:.2f}"
)

fig_hist.add_annotation(
    text=statistics_text,
    xref="paper", yref="paper",
    x=0.5, y=-0.15,  # Shifting below the histogram
    showarrow=False,
    font=dict(size=12, color='black'),
    align="center",  # Center the text
    bordercolor="black",
    borderwidth=1,
    borderpad=6,
    bgcolor="rgba(255, 255, 255, 0.85)",  # Semi-transparent white background
    opacity=0.9
)
"""

# Display the histogram
fig_hist.show()

from plotly.io import write_html

# Save the figure as an HTML file
fig_hist_url = '../report/fig_hist.html'
write_html(fig_hist, file=fig_hist_url, auto_open=False)

In [51]:
# Create bar plot for top 10 regions with the highest number of unique localized titles using Plotly
fig_bar = px.bar(
    region_counts.reset_index(), 
    x='titleId', 
    y='region', 
    orientation='h', 
    title='Top 10 Regions with the Highest Number of Unique Localized Titles',
    labels={'titleId': 'Number of Unique Titles', 'region': 'Region'},
    color='titleId',
    color_continuous_scale='viridis'
)

# Display the bar plot
fig_bar.show()

In [ ]:
df = df.assign(genres=df['genres'].str.split(',')).explode('genres')

# Filter data for the period from 1990 to 2024
df_filtered = df[(df['startYear'] >= 1990) & (df['startYear'] <= 2024)]

# Group by year and genre, then calculate the average rating
df_grouped = df_filtered.groupby(['startYear', 'genres']).mean().reset_index()

# Create the line plot
fig_line = px.line(
    df_grouped,
    x='startYear',
    y='averageRating',
    color='genres',
    title='Average Movie Ratings Over Time by Genre',
    labels={'startYear': 'Year', 'averageRating': 'Average Rating', 'genres': 'Genre'}
)

# Add interactivity and styling
fig_line.update_layout(
    xaxis_title='Year',
    yaxis_title='Average Rating',
    legend_title='Genre',
    autosize=True,
    margin=dict(l=50, r=50, t=50, b=50)
)

# Display the interactive line plot
fig_line.show()

In [ ]:

# Pivot the data for heatmap
pivot_table = region_language_ratings.pivot(index='region', columns='language', values='averageRating')

# Create the interactive heatmap using Plotly
fig_heatmap = px.imshow(
    pivot_table,
    labels=dict(x="Language", y="Region", color="Average Rating"),
    x=pivot_table.columns,
    y=pivot_table.index,
    zmin=pivot_table.min().min(),
    zmax=pivot_table.max().max(),
    color_continuous_scale="Viridis"
)

# Add interactivity and styling
fig_heatmap.update_layout(
    title="Interactive Heatmap: Average IMDb Ratings by Region and Language",
    title_font_size=16,
    xaxis_title="Language",
    yaxis_title="Region",
    xaxis=dict(tickangle=45),
    coloraxis_colorbar=dict(title="Avg Rating"),
    autosize=True,
    margin=dict(l=50, r=50, t=50, b=50)
)

# Display the interactive heatmap
fig_heatmap.show()